// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: accounts.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountInputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int32                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountInputRequest) Reset() {
	*x = AccountInputRequest{}
	mi := &file_accounts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInputRequest) ProtoMessage() {}

func (x *AccountInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInputRequest.ProtoReflect.Descriptor instead.
func (*AccountInputRequest) Descriptor() ([]byte, []int) {
	return file_accounts_proto_rawDescGZIP(), []int{0}
}

func (x *AccountInputRequest) GetAccountId() int32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type CreateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int32                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	SessionToken  string                 `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_accounts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_accounts_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAccountResponse) GetAccountId() int32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *CreateAccountResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type IsTokenExpiredResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expired       bool                   `protobuf:"varint,1,opt,name=expired,proto3" json:"expired,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsTokenExpiredResponse) Reset() {
	*x = IsTokenExpiredResponse{}
	mi := &file_accounts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsTokenExpiredResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsTokenExpiredResponse) ProtoMessage() {}

func (x *IsTokenExpiredResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsTokenExpiredResponse.ProtoReflect.Descriptor instead.
func (*IsTokenExpiredResponse) Descriptor() ([]byte, []int) {
	return file_accounts_proto_rawDescGZIP(), []int{2}
}

func (x *IsTokenExpiredResponse) GetExpired() bool {
	if x != nil {
		return x.Expired
	}
	return false
}

type TokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionToken  string                 `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	mi := &file_accounts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResponse.ProtoReflect.Descriptor instead.
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return file_accounts_proto_rawDescGZIP(), []int{3}
}

func (x *TokenResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

var File_accounts_proto protoreflect.FileDescriptor

const file_accounts_proto_rawDesc = "" +
	"\n" +
	"\x0eaccounts.proto\x12\x02v1\"4\n" +
	"\x13AccountInputRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x05R\taccountId\"[\n" +
	"\x15CreateAccountResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x05R\taccountId\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\"2\n" +
	"\x16IsTokenExpiredResponse\x12\x18\n" +
	"\aexpired\x18\x01 \x01(\bR\aexpired\"4\n" +
	"\rTokenResponse\x12#\n" +
	"\rsession_token\x18\x01 \x01(\tR\fsessionToken2\x8c\x02\n" +
	"\aAccount\x12C\n" +
	"\rCreateAccount\x12\x17.v1.AccountInputRequest\x1a\x19.v1.CreateAccountResponse\x126\n" +
	"\bGetToken\x12\x17.v1.AccountInputRequest\x1a\x11.v1.TokenResponse\x12E\n" +
	"\x0eIsTokenExpired\x12\x17.v1.AccountInputRequest\x1a\x1a.v1.IsTokenExpiredResponse\x12=\n" +
	"\x0fRegenerateToken\x12\x17.v1.AccountInputRequest\x1a\x11.v1.TokenResponseB@Z>github.com/chetan-99/account-cred-manager-go-grpc/api/proto/v1b\x06proto3"

var (
	file_accounts_proto_rawDescOnce sync.Once
	file_accounts_proto_rawDescData []byte
)

func file_accounts_proto_rawDescGZIP() []byte {
	file_accounts_proto_rawDescOnce.Do(func() {
		file_accounts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_accounts_proto_rawDesc), len(file_accounts_proto_rawDesc)))
	})
	return file_accounts_proto_rawDescData
}

var file_accounts_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_accounts_proto_goTypes = []any{
	(*AccountInputRequest)(nil),    // 0: v1.AccountInputRequest
	(*CreateAccountResponse)(nil),  // 1: v1.CreateAccountResponse
	(*IsTokenExpiredResponse)(nil), // 2: v1.IsTokenExpiredResponse
	(*TokenResponse)(nil),          // 3: v1.TokenResponse
}
var file_accounts_proto_depIdxs = []int32{
	0, // 0: v1.Account.CreateAccount:input_type -> v1.AccountInputRequest
	0, // 1: v1.Account.GetToken:input_type -> v1.AccountInputRequest
	0, // 2: v1.Account.IsTokenExpired:input_type -> v1.AccountInputRequest
	0, // 3: v1.Account.RegenerateToken:input_type -> v1.AccountInputRequest
	1, // 4: v1.Account.CreateAccount:output_type -> v1.CreateAccountResponse
	3, // 5: v1.Account.GetToken:output_type -> v1.TokenResponse
	2, // 6: v1.Account.IsTokenExpired:output_type -> v1.IsTokenExpiredResponse
	3, // 7: v1.Account.RegenerateToken:output_type -> v1.TokenResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_accounts_proto_init() }
func file_accounts_proto_init() {
	if File_accounts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_accounts_proto_rawDesc), len(file_accounts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_accounts_proto_goTypes,
		DependencyIndexes: file_accounts_proto_depIdxs,
		MessageInfos:      file_accounts_proto_msgTypes,
	}.Build()
	File_accounts_proto = out.File
	file_accounts_proto_goTypes = nil
	file_accounts_proto_depIdxs = nil
}
